### ISSUE TITLE
@keone can you review, please?

### ISSUE THREAD

**Issue by PrinceAnwer** [wormhole-foundation/wormhole-token-list#264]
@keone can you review, please?

_Originally posted by @hudishkin in https://github.com/wormhole-foundation/wormhole-token-list/issues/234#issuecomment-1867689690_
            
```[tasklist]
### Tasks
- [ ] https://github.com/wormhole-foundation/wormhole-token-list/pull/263
- [ ] https://github.com/wormhole-foundation/wormhole-token-list/pull/234
- [ ] https://github.com/wormhole-foundation/wormhole-token-list/pull/261
- [ ] https://github.com/wormhole-foundation/wormhole-token-list/pull/262
- [ ] https://github.com/wormhole-foundation/wormhole-token-list/pull/259
- [ ] https://github.com/wormhole-foundation/wormhole-token-list/pull/260
- [ ] https://github.com/wormhole-foundation/wormhole-token-list/pull/258
```
